### ISSUE TITLE
Why force host cert refresh?

### ISSUE THREAD

**Issue by aeijdenberg** [govau/cga-deploy-k8s#1]
We shouldn't need this line:

https://github.com/govau/cga-deploy-k8s/blob/6e6c172cf683fc4103cf84346d12c160267adcde/installers/0-platform/deploy.sh#L24

i.e. a new jumpbox already will fetch a host cert within 2 minutes of booting up.

Is there a reason why we are calling it in this script?

**Comment by gordcorp** [comment]
As discussed - will remove the host cert refresh, and wait for the jumpbox to be up.
